//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLZWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLZTabelle
    {
        public string BLZ { get; set; }
        public Nullable<short> Merkmal { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<int> PLZ { get; set; }
        public string Ort { get; set; }
        public string Kurzbezeichnung { get; set; }
        public Nullable<int> PAN { get; set; }
        public string BIC { get; set; }
        public string Pruefzifferberechnungsmethode { get; set; }
        public Nullable<int> Datensatznummer { get; set; }
        public string Aenderungskennzeichen { get; set; }
        public Nullable<short> Bankleitzahlloeschung { get; set; }
        public string NachfolgeBLZ { get; set; }
        public int ID { get; set; }


        public override string ToString()
        {
            return String.Format("{0}\n{1}\n{2}\n{3}", this.Bezeichnung, this.BIC, this.PLZ, this.Ort);
        }

    }
}
